######################################################################
# Automatically generated by qmake (3.0) Sun Sep 20 15:14:39 2015
######################################################################

TEMPLATE = app
TARGET = ColorSource
QT += core gui widgets
INCLUDEPATH += .
QMAKE_CXXFLAGS += -std=c++11 -Wall -pedantic

# Input
HEADERS += colorsender.h mainwindow.h timer.h matrix.h rpc.h rgb.h
SOURCES += colorsender.cpp main.cpp mainwindow.cpp timer.cpp rpc.cpp
